name: Build macOS Executable

on:
  push:
    branches: [master]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Usamos Python 3.12 como en el desarrollo original

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller for x86_64
        run: |
          arch -x86_64 python -m PyInstaller Gestion_frenceken.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable-x86_64
          path: dist/

